# Demo Session 1
## Why Numpy?
### Python list is Flexible but not Fast


In [1]:
import sys

l = [1, 2, 3, 4, 5]
print("List:", l)
print("Type of 1st ele:", type(lst[0]))
print("Memory per ele:", sys.getsizeof(lst[0]))
print("Total memory:", sys.getsizeof(lst))


List: [1, 2, 3, 4, 5]
Type of first element: <class 'int'>
Memory per element: 28
Total memory: 104


### Python array Module – Fixed Type but Limited

In [4]:
import array

arr = array.array('i', [1, 2, 3, 4, 5])
print("Array:", arr)
print("Type of first element:", type(arr[0]))


Array: array('i', [1, 2, 3, 4, 5])
Type of first element: <class 'int'>


### NumPy Arrays – Fast, Compact, Powerful

In [5]:
import numpy as np

np_arr = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", np_arr)
print("Type of first element:", type(np_arr[0]))
print("Memory per element:", np_arr.itemsize)
print("Total memory:", np_arr.nbytes)


NumPy Array: [1 2 3 4 5]
Type of first element: <class 'numpy.int64'>
Memory per element: 8
Total memory: 40


### Performance Comparison

In [11]:
import time

big_list = list(range(1000000))
start = time.time()
sum(big_list)
print("Python list sum time:", time.time() - start)

big_np = np.arange(1000000)
start = time.time()
np.sum(big_np)
print("NumPy array sum time:", time.time() - start)


Python list sum time: 0.009799718856811523
NumPy array sum time: 0.0


### Questions
#### What happens if you mix types in a NumPy array?


In [12]:
import numpy as np

arr = np.array([1, 2.5, 'three'])
print(arr)           
print(arr.dtype)     # <U32 (Unicode string)


['1' '2.5' 'three']
<U32


#### Can you do math directly on a Python list?

In [15]:
lst = [1, 2, 3]
print(lst * 2)        # [1, 2, 3, 1, 2, 3] – list repetition
# print(lst + 1) 

[1, 2, 3, 1, 2, 3]


#### What does np.array([1, '2', 3.0]).dtype return?

In [16]:
arr = np.array([1, '2', 3.0])
print(arr)
print(arr.dtype)

['1' '2' '3.0']
<U32


## Creating Arrays from Python Lists


### Basic Array Creation

In [17]:
import numpy as np

lst = [1, 2, 3, 4]
arr = np.array(lst)
print("Array:", arr)
print("Type:", type(arr))
print("Data type:", arr.dtype)


Array: [1 2 3 4]
Type: <class 'numpy.ndarray'>
Data type: int64


### Nested Lists → Multidimensional Arrays

In [18]:
nested = [[1, 2], [3, 4]]
arr2d = np.array(nested)
print("2D Array:\n", arr2d)
print("Shape:", arr2d.shape)


2D Array:
 [[1 2]
 [3 4]]
Shape: (2, 2)


### Explicit dtype Control

In [19]:
arr_float = np.array([1, 2, 3], dtype=float)
print("Float Array:", arr_float)
print("Data type:", arr_float.dtype)


Float Array: [1. 2. 3.]
Data type: float64


In [21]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Creating array from Scratch


In [23]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [24]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))


array([[0.46810639, 0.32340685, 0.60374496],
       [0.62658452, 0.61927572, 0.6139466 ],
       [0.7222453 , 0.76053457, 0.66654941]])

In [27]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))


array([[ 1.59265914, -0.8869041 , -0.27125059],
       [-0.99635947,  1.10577389, -0.66799152],
       [ 0.01933182,  1.9788186 , -1.25655071]])

In [28]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))


array([[2, 9, 9],
       [5, 9, 7],
       [3, 7, 4]], dtype=int32)

In [29]:
# Create a 3x3 identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
# Create an uninitialized array of three integers
np.empty(3)


array([1., 1., 1.])

## NumPy Standard Data Types

In [61]:
# Specifying dtype using string
np.zeros(10, dtype='int16')

# Specifying dtype using NumPy object
np.zeros(10, dtype=np.int16)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

### Common NumPy Data Types

| Type      | Description                      | Example dtype     |
|-----------|----------------------------------|-------------------|
| `bool_`   | Boolean (True or False)          | `np.bool_`        |
| `int_`    | Default integer (platform-based) | `np.int32`, `np.int64` |
| `uint`    | Unsigned integer                 | `np.uint8`, `np.uint16` |
| `float_`  | Floating point                   | `np.float32`, `np.float64` |
| `complex_`| Complex numbers                  | `np.complex64`, `np.complex128` |
| `str_`    | Fixed-length string              | `np.str_`         |
| `object_` | Arbitrary Python objects         | `np.object_`      |

Use smaller types (e.g., `int8`, `float32`) for memory efficiency.  
Use larger types (e.g., `int64`, `float64`) for precision.



### Type Casting
Use `.astype()` to convert between types.  
Note: Casting from float to int truncates decimals.


In [62]:
# Cast float array to int
arr = np.array([1.7, 2.3, 3.9], dtype=np.float32)
arr.astype(np.int32)


array([1, 2, 3], dtype=int32)

## Numpy Attributes

### Creating Arrays of Different Dimensions
We use `np.random.randint()` to generate random integers.  
Seeding ensures reproducibility.  
We'll explore attributes of 1D, 2D, and 3D arrays.


In [73]:
import numpy as np

x1 = np.random.randint(10, size=6)         # 1D array
x2 = np.random.randint(10, size=(3, 4))    # 2D array
x3 = np.random.randint(10, size=(3, 4, 5)) # 3D array

print("x1 (1D array):")
print(x1)

print("\nx2 (2D array):")
print(x2)

print("\nx3 (3D array):")
print(x3)


x1 (1D array):
[6 3 3 7 3 7]

x2 (2D array):
[[2 4 7 5]
 [2 4 3 7]
 [3 9 0 7]]

x3 (3D array):
[[[5 8 7 0 7]
  [7 1 1 3 9]
  [5 6 9 4 3]
  [0 6 6 2 3]]

 [[4 6 8 6 5]
  [5 1 2 3 1]
  [6 2 4 1 2]
  [0 1 2 3 5]]

 [[3 1 7 4 7]
  [5 3 1 8 7]
  [0 9 2 4 6]
  [8 2 1 9 5]]]


### Array Dimensionality, Shape, and Size

- `ndim`: Number of dimensions  
- `shape`: Size of each dimension  
- `size`: Total number of elements

These attributes help you understand the structure of your data.


In [64]:
print("x1 ndim:", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size:", x1.size)

print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size:", x2.size)

print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)


x1 ndim: 1
x1 shape: (6,)
x1 size: 6
x2 ndim: 2
x2 shape: (3, 4)
x2 size: 12
x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


### Data Type (`dtype`)
Shows the type of elements stored in the array.  
In this case, it's `int64` — 64-bit integers.


In [65]:
print("x3 dtype:", x3.dtype)


x3 dtype: int32


### Memory Attributes

- `itemsize`: Size of one element in bytes  
- `nbytes`: Total memory used by the array

✅ `nbytes = itemsize × size` — useful for memory profiling.


In [66]:
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")
print("Expected nbytes:", x3.itemsize * x3.size)


x3 itemsize: 4 bytes
x3 nbytes: 240 bytes
Expected nbytes: 240


### Why These Attributes Matter

- `shape` and `ndim` are essential for reshaping and broadcasting.
- `dtype` affects precision and compatibility.
- `nbytes` helps optimize memory usage in large datasets.

These attributes are foundational for efficient NumPy workflows.


## Array Indexing and Slicing in NumPy

### Array Creation & Basic Indexing

- **1D indexing**: use a single integer to pick an element.
- **2D indexing**: use `[row, col]` to pick one element;  
  a single index on a 2D array returns a full row;  
  `:` selects all elements along that axis.

Before slicing subarrays, it’s crucial to be comfortable with this basic element access.


In [91]:
import numpy as np
np.random.seed(0)

# Create sample arrays
x  = np.arange(10)                      # 1D array: [0,1,…,9]
x2 = np.random.randint(0, 10, size=(3, 4))  # 2D array: shape (3,4)

# Display arrays
print("x  =", x)
print("x2 =\n", x2)

# 1D indexing
print("\n— 1D Indexing —")
print("x[0]   →", x[0])    # first element
print("x[5]   →", x[5])    # sixth element
print("x[-1]  →", x[-1])   # last element

# 2D indexing
print("\n— 2D Indexing —")
print("x2[0, 0] →", x2[0, 0])  # element at row 0, col 0
print("x2[1, 2] →", x2[1, 2])  # element at row 1, col 2
print("x2[2]    →", x2[2])     # entire third row
print("x2[:, 3] →", x2[:, 3])  # entire fourth column


x  = [0 1 2 3 4 5 6 7 8 9]
x2 =
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]

— 1D Indexing —
x[0]   → 0
x[5]   → 5
x[-1]  → 9

— 2D Indexing —
x2[0, 0] → 5
x2[1, 2] → 3
x2[2]    → [2 4 7 6]
x2[:, 3] → [3 5 6]


### 1D Slicing

- `x[:5]` takes elements `0–4`  
- `x[5:]` takes elements `5–9`  
- `x[4:7]` takes elements `4,5,6`  
- Negative and step slicing lets us skip or reverse elements  
- **Interactive:** What does `x[3:9:2]` return? Try it before moving on.


In [81]:
print("x[:5]   →", x[:5])    # first five elements
print("x[5:]   →", x[5:])    # elements from index 5 onward
print("x[4:7]  →", x[4:7])   # indices 4,5,6
print("x[::2]  →", x[::2])   # every other element
print("x[1::2] →", x[1::2])  # every other, starting at 1


x[:5]   → [0 1 2 3 4]
x[5:]   → [5 6 7 8 9]
x[4:7]  → [4 5 6]
x[::2]  → [0 2 4 6 8]
x[1::2] → [1 3 5 7 9]


### Reversing with Negative Step

- `x[::-1]` reverses the array  
- `x[start::-step]` walks backwards from `start`  
- **Tricky:** What happens if you omit `start` in `x[::-2]`? (It starts from end, stepping by -2.)


In [82]:
print("x[::-1]   →", x[::-1])     # reverse entire array
print("x[5::-2] →", x[5::-2])    # from index 5 down to 0, every other


x[::-1]   → [9 8 7 6 5 4 3 2 1 0]
x[5::-2] → [5 3 1]


### 2D Slicing

- Comma-separated slices: `x2[row_slice, col_slice]`  
- `x2[:2, :3]` extracts a 2×3 block  
- `x2[:3, ::2]` takes all rows, columns 0,2,…  
- **Interactive:** Predict `x2[1:3, 1:4:2]` before running it.


In [85]:
print("x2[:2, :3]  →\n", x2[:2, :3])   # first two rows, first three columns
print("x2[:3, ::2] →\n", x2[:3, ::2])  # all rows, every other column


x2[:2, :3]  →
 [[5 0 3]
 [7 9 3]]
x2[:3, ::2] →
 [[5 3]
 [7 3]
 [2 7]]


### Reversing Rows and Columns

- `[::-1, ::-1]` flips both dimensions  
- Handy for rotating images or matrices by 180°  
- **Tip:** Combine with other slices to extract mirrored subarrays.


In [86]:
print("x2[::-1, ::-1] →\n", x2[::-1, ::-1])


x2[::-1, ::-1] →
 [[6 7 4 2]
 [5 3 9 7]
 [3 3 0 5]]


### Accessing Rows and Columns

- `x2[:, 0]` is a 1D view of column 0  
- `x2[1, :]` or `x2[1]` is row 1  
- Omitting the second index defaults to `:`  
- **Tricky:** What is the shape of `x2[:, 0]` vs `x2[0, :]`?


In [87]:
print("First column:", x2[:, 0])
print("Second row:  ", x2[1, :])
print("Row vs slice:", x2[2], x2[2, :])


First column: [5 7 2]
Second row:   [7 9 3 5]
Row vs slice: [2 4 7 6] [2 4 7 6]


### Views vs. Copies

- Slicing returns a **view** — it shares memory with the original  
- Modifying `x2_sub` also changes `x2`  
- Efficient for large data, but be cautious when mutating views.


In [88]:
x2_sub = x2[:2, :2]
print("Subarray before:\n", x2_sub)
x2_sub[0, 0] = 99
print("Subarray after:\n", x2_sub)
print("Original x2 changed:\n", x2)


Subarray before:
 [[5 0]
 [7 9]]
Subarray after:
 [[99  0]
 [ 7  9]]
Original x2 changed:
 [[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


### Copying Data

- Use `.copy()` to get an independent array  
- Changes to the copy do **not** affect the original  
- Useful when you need to preserve the source data unmodified.


In [90]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0, 0] = 42

print("Copy after change:\n", x2_sub_copy)
print("Original x2 remains:\n", x2)


Copy after change:
 [[42  0]
 [ 7  9]]
Original x2 remains:
 [[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


## Reshaping of Arrays

Reshapes a flat array of numbers 1–9 into a 3×3 grid.
Useful for creating matrix-like structures from linear data.


In [92]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Reshape only works when the number of elements matches the target shape.
Mismatch triggers an error — 8 items can’t reshape to shape (3, 3).


In [102]:
x = np.arange(8)
x.reshape((2, 4))   #  valid
# x.reshape((3, 3)) #  ValueError: total size mismatch


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Creates a 1×3 row vector using two equivalent methods.
Both add a new axis to turn the 1D array into a 2D row.


In [99]:
x = np.array([1, 2, 3])
row1 = x.reshape((1, 3))
row2 = x[np.newaxis, :]

row2


array([[1, 2, 3]])

Transforms the same array into a 3×1 column vector.
`np.newaxis` is syntactic sugar for adding dimensions.


In [101]:
col1 = x.reshape((3, 1))
col2 = x[:, np.newaxis]

col2


array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

Joins multiple 1D arrays into one. Works with any number of arrays as long as shapes align.


In [103]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([99, 99, 99])
np.concatenate([x, y, z])


array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

Concatenates 2D arrays:
- `axis=0` stacks rows (adds vertical slices).
- `axis=1` stacks columns (adds horizontal slices).


In [112]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

x1 = np.concatenate([grid, grid])          # axis=0
x2 = np.concatenate([grid, grid], axis=1)  # axis=1

x2


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Use `vstack` for vertical stacking (adds rows),
and `hstack` for horizontal stacking (adds columns).
Handles shape mismatches more cleanly than `concatenate`.


In [113]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
y = np.array([[99],
              [99]])

x1 = np.vstack([x, grid])
np.hstack([grid, y])
x1

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

Splits 1D array at given indices.
- With N split points, produces N+1 subarrays.


In [110]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x1, x2, x3 = np.split(x, [3, 5])

x1,x2,x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

- `vsplit` splits vertically (along rows).
- `hsplit` splits horizontally (along columns).
Each takes split indices for precise slicing.


In [111]:
grid = np.arange(16).reshape((4, 4))

upper, lower = np.vsplit(grid, [2])
left, right = np.hsplit(grid, [2])

upper,lower,left,right

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

## NumPy's UFuncs

### Arithmetic Operators
Applies element-wise math with scalars:
- `+`, `-`, `*`, `/`, `//` use NumPy's fast vectorized operations.
- Internally mapped to `np.add`, `np.subtract`, `np.multiply`, etc.


In [117]:
import numpy as np

x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
# Explicit ufunc version
print("np.add(x, 2):", np.add(x, 2))

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
np.add(x, 2): [2 3 4 5]


### Unary Operations
- `-x`: negation → `np.negative`
- `**`: power → `np.power`
- `%`: modulus → `np.mod`
All respect Python’s operator precedence.


In [118]:
print("-x     =", -x)
print("x ** 2 =", x ** 2)
print("x % 2  =", x % 2)


-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]


### Absolute Value
- `np.abs` or `np.absolute` handles real or complex numbers.
- Returns magnitude for complex inputs.


In [119]:
x_real = np.array([-2, -1, 0, 1, 2])
print("np.abs(real):", np.abs(x_real))

x_cmplx = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
print("np.abs(complex):", np.abs(x_cmplx))


np.abs(real): [2 1 0 1 2]
np.abs(complex): [5. 5. 2. 1.]


### Trigonometry
- Element-wise sin, cos, tan of angles in radians.
- Values respect machine precision.


In [121]:
theta = np.linspace(0, np.pi, 3)
print("sin:", np.sin(theta))
print("cos:", np.cos(theta))
print("tan:", np.tan(theta))


sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


### Exponentials
- `np.exp`: e raised to x
- `np.exp2`: 2 raised to x
- `np.power(base, x)`: any base to power x


In [122]:
x = np.array([1, 2, 3])
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))


e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


### Specifying Output
Use the `out=` parameter to write results directly to an existing array.
Saves memory by avoiding temporary arrays—especially valuable for large data.


In [123]:
import numpy as np

x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print("y after multiply:", y)


y after multiply: [ 0. 10. 20. 30. 40.]


### Array Views as Output Targets
You can target array slices or views with `out=` to update selective elements.
Efficient for custom memory layouts or sparse updates.


In [124]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print("y after power with view:", y)


y after power with view: [ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


### Aggregates with `.reduce()`
- Applies operation across array to return a single value.
- Examples: sum → `np.add.reduce`; product → `np.multiply.reduce`


In [125]:
x = np.arange(1, 6)
print("np.add.reduce:", np.add.reduce(x))
print("np.multiply.reduce:", np.multiply.reduce(x))


np.add.reduce: 15
np.multiply.reduce: 120


### Aggregates with `.accumulate()`
Returns intermediate results:
- Cumulative sum → `np.add.accumulate`
- Cumulative product → `np.multiply.accumulate`
Identical to: `np.cumsum`, `np.cumprod`


In [126]:
print("np.add.accumulate:", np.add.accumulate(x))
print("np.multiply.accumulate:", np.multiply.accumulate(x))


np.add.accumulate: [ 1  3  6 10 15]
np.multiply.accumulate: [  1   2   6  24 120]


## Aggregations

### `np.sum` vs Python `sum`

Use `np.sum()` instead of Python’s built-in `sum()` for performance and better multidimensional support.





In [127]:
import numpy as np

big_array = np.random.rand(1_000_000)

# Python's built-in sum (slow)
%timeit sum(big_array)

# NumPy's optimized sum
%timeit np.sum(big_array)


94.6 ms ± 1.65 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
586 μs ± 39 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Fast Min & Max

Use `np.min()` and `np.max()` over Python’s `min()`/`max()` for speed.

You can also use `.min()` and `.max()` directly on NumPy arrays.


In [128]:
# Python built-in
%timeit min(big_array)

# NumPy optimized
%timeit np.min(big_array)

# Shorter syntax
print(big_array.min(), big_array.max())


60.6 ms ± 2.57 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
597 μs ± 5.05 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
1.4057692298008462e-06 0.9999994392723005


### Aggregation with Axes

- `axis=0`: collapse down rows → operate on columns  
- `axis=1`: collapse down columns → operate on rows  
Example: `min(axis=0)` returns column-wise minimums.


In [130]:
M = np.random.random((3, 4))
print(M)
print("Sum:", M.sum())               # Total sum
print("Col min:", M.min(axis=0))     # Min in each column
print("Row max:", M.max(axis=1))     # Max in each row


[[0.79944159 0.55365709 0.80754132 0.60969576]
 [0.36284768 0.36196542 0.94772432 0.68212345]
 [0.44300384 0.61008711 0.04031012 0.25867995]]
Sum: 6.477077660389182
Col min: [0.36284768 0.36196542 0.04031012 0.25867995]
Row max: [0.80754132 0.94772432 0.61008711]


### Basic Statistical Aggregates

- `mean()`: average  
- `std()`: standard deviation  
- `median()`: middle value  
Great for descriptive analysis.


In [131]:
print("Mean:", M.mean())
print("Std Dev:", M.std())
print("Median:", np.median(M))


Mean: 0.5397564716990985
Std Dev: 0.24775667796616746
Median: 0.5816764244588959


### NaN-Safe Functions

Use `np.nan*` versions like `np.nanmean`, `np.nanmin`, etc.  
They skip over NaN values — useful in dirty or incomplete datasets.


In [132]:
arr = np.array([1.0, np.nan, 2.0, np.nan])

print("np.mean:", np.mean(arr))         # Gives nan
print("np.nanmean:", np.nanmean(arr))   # Skips NaNs


np.mean: nan
np.nanmean: 1.5


### Logical Aggregates

- `np.any`: returns True if **any** element is true  
- `np.all`: returns True only if **all** are true  
Helpful for condition checks and flag logic.


In [133]:
bools = np.array([False, True, True])

print("Any true?", np.any(bools))
print("All true?", np.all(bools))


Any true? True
All true? False


## Broadcasting


### Simple Broadcasting
A scalar (`b`) is broadcast to each element in the array `a`.  
➡️ Result: `[11 12 13]`


In [136]:
import numpy as np

a = np.array([1, 2, 3])
b = 10

print("a + b:", a + b)


a + b: [11 12 13]


### Rules
NumPy compares shapes from **right to left** and applies these rules:

1. If dimensions differ, **pad the smaller shape with 1s on the left**.
2. Dimensions are **compatible** when they are:
   - Equal, or
   - One of them is 1
3. The result shape is the **element-wise maximum** of input shapes.

📌 Broadcasting expands size-1 dimensions to match the other — but doesn't copy data in memory.


### Applying the Rules
Shapes:
- `A`: (3,1)
- `B`: (4,) → treated as (1,4)

Align right:
A : (3,1)
B : (1,4)
→ Compatible → broadcasted shape: (3,4)

In [137]:
A = np.ones((3, 1))   # shape (3,1)
B = np.arange(4)      # shape (4,)

C = A + B             # shape (3,4)
print("Result C:\n", C)


Result C:
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


### Broadcasting Failure Example

Shapes:
- `A`: (3,2)
- `B`: (2,3)

Alignment:

A : (3,2)
B : (2,3)
→ Not compatible: No dimension is equal or 1 at each position

In [138]:
import numpy as np

A = np.ones((3, 2))    # shape (3,2)
B = np.ones((2, 3))    # shape (2,3)

# This will raise a ValueError
C = A + B


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

## Boolmasking and comparisons

### 🔍 Basic Comparison + Boolean Masking

- `a > 5` creates a Boolean array: `[False, True, False, True, False]`
- Using this as a mask: `a[mask] → [7, 9]`

🧠 Use comparisons (`>`, `<`, `==`, `!=`, etc.) to generate masks  
📌 Masks are just arrays of `True` or `False` values


In [139]:
import numpy as np

a = np.array([3, 7, 2, 9, 5])

mask = a > 5
print("Mask:", mask)
print("Filtered result:", a[mask])


Mask: [False  True False  True False]
Filtered result: [7 9]


### 🔗 Compound Conditions

- Combine masks using:
  - `&` for AND
  - `|` for OR
  - `~` for NOT

🚫 Don’t use Python’s `and` / `or`—use NumPy’s bitwise operators instead!

➡️ `(a > 4) & (a < 8)` → `[False, True, False, False, True]`
Filtered result: `[7, 5]`


In [140]:
a = np.array([3, 7, 2, 9, 5])

# Elements > 4 AND < 8
mask = (a > 4) & (a < 8)
print("Filtered:", a[mask])


Filtered: [7 5]


###  Masking Failure: Shape Mismatch

- `a`: shape `(2, 2)`
- `mask`: shape `(3,)` → incompatible!

 NumPy will raise:
`IndexError: boolean index did not match indexed array`


In [141]:
a = np.array([[1, 2], [3, 4]])
mask = np.array([True, False, True])  # Shape mismatch

a[mask]  # ❌ Will raise IndexError


IndexError: boolean index did not match indexed array along axis 0; size of axis is 2 but size of corresponding boolean axis is 3

## Fancy Indexing

### 🎯 Fancy Indexing (Integer-based)

- You use a list or array of integers to fetch specific elements.
- `a[[0, 3, 4]]` → `[10, 40, 50]`

🧠 Fancy indexing doesn’t change the original array—it creates a new one.


In [142]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

indices = [0, 3, 4]
selected = a[indices]

print("Selected values:", selected)


Selected values: [10 40 50]


### 🎲 Fancy Indexing (2D)

- `a[[0, 2], [1, 0]]` selects:
  - Element at (0,1): 12
  - Element at (2,0): 15
➡️ Output: `[12, 15]`

📌 When indexing both axes: the i-th item in each list is combined into a coordinate.


In [143]:
a = np.array([[11, 12], [13, 14], [15, 16]])

rows = [0, 2]
cols = [1, 0]

# Select specific element pairs
result = a[rows, cols]
print("Result:", result)


Result: [12 15]


## Sorting in Numpy

###  Sorting with `np.sort()`

- Returns a **sorted copy** of the array (original is unchanged).
- Default: ascending order.

 You can sort along an axis using `np.sort(arr, axis=...)`


In [144]:
import numpy as np

a = np.array([42, 17, 23, 7, 88])

sorted_a = np.sort(a)
print("Sorted array:", sorted_a)


Sorted array: [ 7 17 23 42 88]


###  In-Place Sorting

- `.sort()` modifies the original array directly.
➡️ More memory-efficient than `np.sort()`

 Use when you don't need to preserve the original array


In [145]:
a = np.array([9, 3, 1, 7])
a.sort()
print("In-place sorted:", a)


In-place sorted: [1 3 7 9]


###  Sorting Along Axes

- `axis=1`: sort each row
- `axis=0`: sort each column

 Powerful for matrix-style data cleanup!


In [146]:
a = np.array([[5, 2, 3], [9, 1, 6]])

print("Sort by row:\n", np.sort(a, axis=1))
print("Sort by column:\n", np.sort(a, axis=0))


Sort by row:
 [[2 3 5]
 [1 6 9]]
Sort by column:
 [[5 1 3]
 [9 2 6]]


###  Sorting Indices with `np.argsort()`

- Returns indices that would sort the array.
- Handy for **ranking**, **ordering**, or **custom sorting**.

Example:
- Array: `[50, 20, 30]`
- Indices: `[1, 2, 0]`
➡️ Sorted: `[20, 30, 50]`


In [147]:
a = np.array([50, 20, 30])

idx = np.argsort(a)
print("Indices:", idx)
print("Sorted using indices:", a[idx])


Indices: [1 2 0]
Sorted using indices: [20 30 50]
