# Demo Session 1
## Why Numpy?
### Python list is Flexible but not Fast


In [1]:
import sys

l = [1, 2, 3, 4, 5]
print("List:", l)
print("Type of 1st ele:", type(lst[0]))
print("Memory per ele:", sys.getsizeof(lst[0]))
print("Total memory:", sys.getsizeof(lst))


List: [1, 2, 3, 4, 5]
Type of first element: <class 'int'>
Memory per element: 28
Total memory: 104


### Python array Module – Fixed Type but Limited

In [4]:
import array

arr = array.array('i', [1, 2, 3, 4, 5])
print("Array:", arr)
print("Type of first element:", type(arr[0]))


Array: array('i', [1, 2, 3, 4, 5])
Type of first element: <class 'int'>


### NumPy Arrays – Fast, Compact, Powerful

In [5]:
import numpy as np

np_arr = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", np_arr)
print("Type of first element:", type(np_arr[0]))
print("Memory per element:", np_arr.itemsize)
print("Total memory:", np_arr.nbytes)


NumPy Array: [1 2 3 4 5]
Type of first element: <class 'numpy.int64'>
Memory per element: 8
Total memory: 40


### Performance Comparison

In [11]:
import time

big_list = list(range(1000000))
start = time.time()
sum(big_list)
print("Python list sum time:", time.time() - start)

big_np = np.arange(1000000)
start = time.time()
np.sum(big_np)
print("NumPy array sum time:", time.time() - start)


Python list sum time: 0.009799718856811523
NumPy array sum time: 0.0


### Questions
#### What happens if you mix types in a NumPy array?


In [12]:
import numpy as np

arr = np.array([1, 2.5, 'three'])
print(arr)           
print(arr.dtype)     # <U32 (Unicode string)


['1' '2.5' 'three']
<U32


#### Can you do math directly on a Python list?

In [15]:
lst = [1, 2, 3]
print(lst * 2)        # [1, 2, 3, 1, 2, 3] – list repetition
# print(lst + 1) 

[1, 2, 3, 1, 2, 3]


#### What does np.array([1, '2', 3.0]).dtype return?

In [16]:
arr = np.array([1, '2', 3.0])
print(arr)
print(arr.dtype)

['1' '2' '3.0']
<U32


## Creating Arrays from Python Lists


### Basic Array Creation

In [17]:
import numpy as np

lst = [1, 2, 3, 4]
arr = np.array(lst)
print("Array:", arr)
print("Type:", type(arr))
print("Data type:", arr.dtype)


Array: [1 2 3 4]
Type: <class 'numpy.ndarray'>
Data type: int64


### Nested Lists → Multidimensional Arrays

In [18]:
nested = [[1, 2], [3, 4]]
arr2d = np.array(nested)
print("2D Array:\n", arr2d)
print("Shape:", arr2d.shape)


2D Array:
 [[1 2]
 [3 4]]
Shape: (2, 2)


### Explicit dtype Control

In [19]:
arr_float = np.array([1, 2, 3], dtype=float)
print("Float Array:", arr_float)
print("Data type:", arr_float.dtype)


Float Array: [1. 2. 3.]
Data type: float64


### Trickier Case: Ragged Nested Lists

In [20]:
ragged = [[1, 2], [3, 4, 5]]
arr_ragged = np.array(ragged)
print("Ragged Array:", arr_ragged)
print("Data type:", arr_ragged.dtype)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

## Creating Arrays from Scratch

In [21]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [24]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))


array([[0.46810639, 0.32340685, 0.60374496],
       [0.62658452, 0.61927572, 0.6139466 ],
       [0.7222453 , 0.76053457, 0.66654941]])

In [27]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))


array([[ 1.59265914, -0.8869041 , -0.27125059],
       [-0.99635947,  1.10577389, -0.66799152],
       [ 0.01933182,  1.9788186 , -1.25655071]])

In [28]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))


array([[2, 9, 9],
       [5, 9, 7],
       [3, 7, 4]], dtype=int32)

In [29]:
# Create a 3x3 identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
# Create an uninitialized array of three integers
np.empty(3)


array([1., 1., 1.])

## NumPy Standard Data Types

In [61]:
# Specifying dtype using string
np.zeros(10, dtype='int16')

# Specifying dtype using NumPy object
np.zeros(10, dtype=np.int16)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

### Common NumPy Data Types

| Type      | Description                      | Example dtype     |
|-----------|----------------------------------|-------------------|
| `bool_`   | Boolean (True or False)          | `np.bool_`        |
| `int_`    | Default integer (platform-based) | `np.int32`, `np.int64` |
| `uint`    | Unsigned integer                 | `np.uint8`, `np.uint16` |
| `float_`  | Floating point                   | `np.float32`, `np.float64` |
| `complex_`| Complex numbers                  | `np.complex64`, `np.complex128` |
| `str_`    | Fixed-length string              | `np.str_`         |
| `object_` | Arbitrary Python objects         | `np.object_`      |

Use smaller types (e.g., `int8`, `float32`) for memory efficiency.  
Use larger types (e.g., `int64`, `float64`) for precision.



### Type Casting
Use `.astype()` to convert between types.  
Note: Casting from float to int truncates decimals.


In [62]:
# Cast float array to int
arr = np.array([1.7, 2.3, 3.9], dtype=np.float32)
arr.astype(np.int32)


array([1, 2, 3], dtype=int32)

### ❓ FAQs

**Q1: What happens if I mix types in a list?**  
NumPy will upcast to the most general type to preserve data.

**Q2: Can I store strings or objects in NumPy arrays?**  
Yes, using `np.str_` or `np.object_`, but performance may suffer.

**Q3: How do I check the dtype of an array?**  
Use `.dtype` → `arr.dtype`


## Numpy Attributes

### Creating Arrays of Different Dimensions
We use `np.random.randint()` to generate random integers.  
Seeding ensures reproducibility.  
We'll explore attributes of 1D, 2D, and 3D arrays.


In [73]:
import numpy as np

x1 = np.random.randint(10, size=6)         # 1D array
x2 = np.random.randint(10, size=(3, 4))    # 2D array
x3 = np.random.randint(10, size=(3, 4, 5)) # 3D array

print("x1 (1D array):")
print(x1)

print("\nx2 (2D array):")
print(x2)

print("\nx3 (3D array):")
print(x3)


x1 (1D array):
[6 3 3 7 3 7]

x2 (2D array):
[[2 4 7 5]
 [2 4 3 7]
 [3 9 0 7]]

x3 (3D array):
[[[5 8 7 0 7]
  [7 1 1 3 9]
  [5 6 9 4 3]
  [0 6 6 2 3]]

 [[4 6 8 6 5]
  [5 1 2 3 1]
  [6 2 4 1 2]
  [0 1 2 3 5]]

 [[3 1 7 4 7]
  [5 3 1 8 7]
  [0 9 2 4 6]
  [8 2 1 9 5]]]


### Array Dimensionality, Shape, and Size

- `ndim`: Number of dimensions  
- `shape`: Size of each dimension  
- `size`: Total number of elements

These attributes help you understand the structure of your data.


In [64]:
print("x1 ndim:", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size:", x1.size)

print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size:", x2.size)

print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)


x1 ndim: 1
x1 shape: (6,)
x1 size: 6
x2 ndim: 2
x2 shape: (3, 4)
x2 size: 12
x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


### Data Type (`dtype`)
Shows the type of elements stored in the array.  
In this case, it's `int64` — 64-bit integers.


In [65]:
print("x3 dtype:", x3.dtype)


x3 dtype: int32


### Memory Attributes

- `itemsize`: Size of one element in bytes  
- `nbytes`: Total memory used by the array

✅ `nbytes = itemsize × size` — useful for memory profiling.


In [66]:
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")
print("Expected nbytes:", x3.itemsize * x3.size)


x3 itemsize: 4 bytes
x3 nbytes: 240 bytes
Expected nbytes: 240


### Why These Attributes Matter

- `shape` and `ndim` are essential for reshaping and broadcasting.
- `dtype` affects precision and compatibility.
- `nbytes` helps optimize memory usage in large datasets.

These attributes are foundational for efficient NumPy workflows.


## Array Indexing and Slicing in NumPy

### Array Creation & Basic Indexing

- **1D indexing**: use a single integer to pick an element.
- **2D indexing**: use `[row, col]` to pick one element;  
  a single index on a 2D array returns a full row;  
  `:` selects all elements along that axis.

Before slicing subarrays, it’s crucial to be comfortable with this basic element access.


In [80]:
import numpy as np
np.random.seed(0)

# Create sample arrays
x  = np.arange(10)                      # 1D array: [0,1,…,9]
x2 = np.random.randint(0, 10, size=(3, 4))  # 2D array: shape (3,4)

# Display arrays
print("x  =", x)
print("x2 =\n", x2)

# 1D indexing
print("\n— 1D Indexing —")
print("x[0]   →", x[0])    # first element
print("x[5]   →", x[5])    # sixth element
print("x[-1]  →", x[-1])   # last element

# 2D indexing
print("\n— 2D Indexing —")
print("x2[0, 0] →", x2[0, 0])  # element at row 0, col 0
print("x2[1, 2] →", x2[1, 2])  # element at row 1, col 2
print("x2[2]    →", x2[2])     # entire third row
print("x2[:, 3] →", x2[:, 3])  # entire fourth column


x  = [0 1 2 3 4 5 6 7 8 9]
x2 =
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]

— 1D Indexing —
x[0]   → 0
x[5]   → 5
x[-1]  → 9

— 2D Indexing —
x2[0, 0] → 5
x2[1, 2] → 3
x2[2]    → [2 4 7 6]
x2[:, 3] → [3 5 6]


### 1D Slicing

- `x[:5]` takes elements `0–4`  
- `x[5:]` takes elements `5–9`  
- `x[4:7]` takes elements `4,5,6`  
- Negative and step slicing lets us skip or reverse elements  
- **Interactive:** What does `x[3:9:2]` return? Try it before moving on.


In [81]:
print("x[:5]   →", x[:5])    # first five elements
print("x[5:]   →", x[5:])    # elements from index 5 onward
print("x[4:7]  →", x[4:7])   # indices 4,5,6
print("x[::2]  →", x[::2])   # every other element
print("x[1::2] →", x[1::2])  # every other, starting at 1


x[:5]   → [0 1 2 3 4]
x[5:]   → [5 6 7 8 9]
x[4:7]  → [4 5 6]
x[::2]  → [0 2 4 6 8]
x[1::2] → [1 3 5 7 9]


### Reversing with Negative Step

- `x[::-1]` reverses the array  
- `x[start::-step]` walks backwards from `start`  
- **Tricky:** What happens if you omit `start` in `x[::-2]`? (It starts from end, stepping by -2.)


In [82]:
print("x[::-1]   →", x[::-1])     # reverse entire array
print("x[5::-2] →", x[5::-2])    # from index 5 down to 0, every other


x[::-1]   → [9 8 7 6 5 4 3 2 1 0]
x[5::-2] → [5 3 1]


### 2D Slicing

- Comma-separated slices: `x2[row_slice, col_slice]`  
- `x2[:2, :3]` extracts a 2×3 block  
- `x2[:3, ::2]` takes all rows, columns 0,2,…  
- **Interactive:** Predict `x2[1:3, 1:4:2]` before running it.


In [85]:
print("x2[:2, :3]  →\n", x2[:2, :3])   # first two rows, first three columns
print("x2[:3, ::2] →\n", x2[:3, ::2])  # all rows, every other column


x2[:2, :3]  →
 [[5 0 3]
 [7 9 3]]
x2[:3, ::2] →
 [[5 3]
 [7 3]
 [2 7]]


### Reversing Rows and Columns

- `[::-1, ::-1]` flips both dimensions  
- Handy for rotating images or matrices by 180°  
- **Tip:** Combine with other slices to extract mirrored subarrays.


In [86]:
print("x2[::-1, ::-1] →\n", x2[::-1, ::-1])


x2[::-1, ::-1] →
 [[6 7 4 2]
 [5 3 9 7]
 [3 3 0 5]]


### Accessing Rows and Columns

- `x2[:, 0]` is a 1D view of column 0  
- `x2[1, :]` or `x2[1]` is row 1  
- Omitting the second index defaults to `:`  
- **Tricky:** What is the shape of `x2[:, 0]` vs `x2[0, :]`?


In [87]:
print("First column:", x2[:, 0])
print("Second row:  ", x2[1, :])
print("Row vs slice:", x2[2], x2[2, :])


First column: [5 7 2]
Second row:   [7 9 3 5]
Row vs slice: [2 4 7 6] [2 4 7 6]


### Views vs. Copies

- Slicing returns a **view** — it shares memory with the original  
- Modifying `x2_sub` also changes `x2`  
- Efficient for large data, but be cautious when mutating views.


In [88]:
x2_sub = x2[:2, :2]
print("Subarray before:\n", x2_sub)
x2_sub[0, 0] = 99
print("Subarray after:\n", x2_sub)
print("Original x2 changed:\n", x2)


Subarray before:
 [[5 0]
 [7 9]]
Subarray after:
 [[99  0]
 [ 7  9]]
Original x2 changed:
 [[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


### Copying Data

- Use `.copy()` to get an independent array  
- Changes to the copy do **not** affect the original  
- Useful when you need to preserve the source data unmodified.


In [90]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0, 0] = 42

print("Copy after change:\n", x2_sub_copy)
print("Original x2 remains:\n", x2)


Copy after change:
 [[42  0]
 [ 7  9]]
Original x2 remains:
 [[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]
